source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
inhibit_all_warnings!
use_frameworks!
target 'DQM_ReaderBooks' do

#常用控件⬇️
pod 'AFNetworking', '~> 3.2.1'
pod 'TYCyclePagerView','~> 1.1.0'               #轮播
pod 'ReactiveObjC', '~> 2.1.2'                  #响应式编程
pod 'IQKeyboardManager', '~> 6.1.1'             #控制键盘的高度
pod 'Reachability', '~> 3.2'                    #网络监控插件
pod 'MBProgressHUD', '~> 1.1.0'                 #MB蒙版
pod 'Toast', '~> 4.0.0'                         #不带遮罩蒙版
pod 'Masonry', '~> 1.1.0'                       #控件约束autolayout
pod 'FMDB', '~> 2.7.2'                          #数据库

pod 'MJRefresh', '~> 3.1.15.3'                  #刷新基类
pod 'MJExtension', '~> 3.0.15.1'                #数据转换

pod 'YYText', '~> 1.0.7'                        #YY文字类
pod 'YYCategories', '~> 1.0.4'                  #YY扩展类

pod 'SDWebImage', '~> 4.3.3'                    #加载图片控件
pod 'SDWebImage/GIF'                            #GIF的支持
#常用控件⤴️



end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == 'ReactiveCocoa' || target.name == 'ReactiveSwift' || #target.name == 'TextFieldEffects'
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '3.2'
#                end
#        else
#            target.build_configurations.each do |config|
              #                config.build_settings['SWIFT_VERSION'] = '4.0'
#            end
#        end
#    end
#end
